# Generated by Django 5.2.5 on 2025-08-27 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('dynasty', models.CharField(blank=True, max_length=50, verbose_name='朝代')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='页码')),
                ('image', models.ImageField(upload_to='book_pages/', verbose_name='页面图片')),
                ('ocr_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='OCR状态')),
                ('ocr_confidence', models.FloatField(blank=True, null=True, verbose_name='OCR置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='books.book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '书页',
                'verbose_name_plural': '书页',
                'ordering': ['page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='OCRTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookpage', verbose_name='页面')),
            ],
            options={
                'verbose_name': 'OCR任务',
                'verbose_name_plural': 'OCR任务',
            },
        ),
        migrations.CreateModel(
            name='TextRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(max_length=50, verbose_name='区域ID')),
                ('x', models.IntegerField(verbose_name='X坐标')),
                ('y', models.IntegerField(verbose_name='Y坐标')),
                ('width', models.IntegerField(verbose_name='宽度')),
                ('height', models.IntegerField(verbose_name='高度')),
                ('original_text', models.TextField(verbose_name='原始识别文本')),
                ('confidence', models.FloatField(verbose_name='识别置信度')),
                ('order_index', models.IntegerField(verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_regions', to='books.bookpage', verbose_name='页面')),
            ],
            options={
                'verbose_name': '文本区域',
                'verbose_name_plural': '文本区域',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TextCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_text', models.TextField(verbose_name='校对后文本')),
                ('correction_notes', models.TextField(blank=True, verbose_name='校对备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='校对时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('corrector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='校对者')),
                ('text_region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='books.textregion', verbose_name='文本区域')),
            ],
            options={
                'verbose_name': '文本校对',
                'verbose_name_plural': '文本校对',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField(verbose_name='翻译文本')),
                ('translation_language', models.CharField(choices=[('zh-cn', '简体中文'), ('en', '英语'), ('ja', '日语')], default='zh-cn', max_length=10, verbose_name='翻译语言')),
                ('translation_method', models.CharField(choices=[('manual', '人工翻译'), ('auto', '机器翻译'), ('hybrid', '人工+机器')], default='auto', max_length=20, verbose_name='翻译方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='翻译时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('text_region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='books.textregion', verbose_name='文本区域')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='翻译者')),
            ],
            options={
                'verbose_name': '翻译',
                'verbose_name_plural': '翻译',
            },
        ),
    ]
